---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# paren

The goal of parens is to offer a utility function `paren()` to build a list of values for SQL IN operator.
`paren()` will add single quote to each element when the data type is not numeric. 

## Install

```
# install.packages('devtools')
devtools::install_github("taekyunk/paren")
```

## Example

This is a basic example of using `paren()` with SQL IN operator.

```{r example}
id_char <- as.character(1:5)
id_num <- 3:8

# paren() will add single quotes if the field is not numeric
paren(id_char)
paren(id_num)

# to match character with numeric
paren(as.numeric(id_char))

# to match numeric with character
paren(as.character(id_num))

# typical use case will be something like this
query <- paste("select * from tablename where id in", paren(id_num), ";")
print(query)
```
